import { useEffect, useRef, useState } from "react";
import { useParams } from "react-router-dom";
import type { EChartsType } from "echarts";
import { Alert, Button, Card, Col, Empty, List, Progress, Row, Skeleton, Space, Tag, Typography, message } from "antd";
import { DownloadOutlined, ReloadOutlined } from "@ant-design/icons";
import { generateReport, getSession } from "../api/client";
import { useSessionStore } from "../store/sessionStore";
import type { InterviewReport, InterviewSession } from "../shared/types";

function downloadMarkdown(report: InterviewReport, session: InterviewSession) {
  const blob = new Blob([report.markdown], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${session.company}-${session.jobTitle}-面试复盘.md`;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function ReportPage() {
  const { sessionId } = useParams();
  const chartRef = useRef<HTMLDivElement>(null);
  const autoGeneratedSessionId = useRef<string>();
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const currentSession = useSessionStore((state) => state.currentSession);
  const reportFromStore = useSessionStore((state) => state.report);
  const setCurrentSession = useSessionStore((state) => state.setCurrentSession);
  const setReportResult = useSessionStore((state) => state.setReportResult);

  useEffect(() => {
    async function loadSession() {
      if (!sessionId) return;

      setLoading(true);
      try {
        setCurrentSession(await getSession(sessionId));
      } catch (error) {
        message.error(error instanceof Error ? error.message : "读取 session 失败");
      } finally {
        setLoading(false);
      }
    }

    if (!currentSession || currentSession.id !== sessionId) {
      void loadSession();
    } else {
      setLoading(false);
    }
  }, [currentSession, sessionId, setCurrentSession]);

  const session = currentSession as InterviewSession | undefined;
  const report = reportFromStore ?? session?.report;
  const practiceCount = session?.practiceRecords?.length ?? 0;
  const activeReport = report;

  useEffect(() => {
    if (!session || activeReport || autoGeneratedSessionId.current === session.id) return;

    autoGeneratedSessionId.current = session.id;
    setGenerating(true);
    generateReport({ sessionId: session.id })
      .then((result) => {
        setReportResult(result);
      })
      .catch((error) => {
        message.error(error instanceof Error ? error.message : "报告生成失败");
      })
      .finally(() => {
        setGenerating(false);
      });
  }, [activeReport, session, setReportResult]);

  useEffect(() => {
    const chartEl = chartRef.current;
    if (!chartEl || !activeReport) return;

    let disposed = false;
    let chart: EChartsType | undefined;
    const handleResize = () => chart?.resize();

    void import("echarts").then((echarts) => {
      if (disposed) return;

      chart = echarts.init(chartEl);
      chart.setOption({
      tooltip: {},
      radar: {
        radius: "66%",
        indicator: activeReport.radarData.map((item) => ({ name: item.name, max: 100 })),
        splitNumber: 4
      },
      series: [
        {
          type: "radar",
          data: [
            {
              value: activeReport.radarData.map((item) => item.value),
              name: "本轮表现",
              areaStyle: { color: "rgba(31, 122, 140, 0.16)" },
              lineStyle: { color: "#1f7a8c" },
              itemStyle: { color: "#1f7a8c" }
            }
          ]
        }
      ]
      });

      window.addEventListener("resize", handleResize);
    });

    return () => {
      disposed = true;
      window.removeEventListener("resize", handleResize);
      chart?.dispose();
    };
  }, [activeReport]);

  const handleGenerate = async () => {
    if (!session) return;

    setGenerating(true);
    try {
      const result = await generateReport({ sessionId: session.id });
      setReportResult(result);
      message.success("复盘报告已生成");
    } catch (error) {
      message.error(error instanceof Error ? error.message : "报告生成失败");
    } finally {
      setGenerating(false);
    }
  };

  if (loading) return <Skeleton active paragraph={{ rows: 10 }} />;
  if (!session) return <Empty description="未找到这份准备记录" />;

  if (!activeReport) {
    return (
      <Empty description="还没有生成复盘报告">
        <Button type="primary" icon={<ReloadOutlined />} onClick={handleGenerate} loading={generating}>
          {generating ? "正在生成" : "生成复盘报告"}
        </Button>
      </Empty>
    );
  }

  return (
    <section className="analysis-page">
      <div className="analysis-heading">
        <div>
          <Typography.Title level={1}>复盘报告</Typography.Title>
          <Typography.Paragraph>
            {session.company} · {session.jobTitle}，已汇总单题评分、薄弱点和下一轮训练计划。
          </Typography.Paragraph>
        </div>
        <Space>
          <Button icon={<ReloadOutlined />} onClick={handleGenerate} loading={generating}>
            重新生成
          </Button>
          <Button icon={<DownloadOutlined />} onClick={() => downloadMarkdown(activeReport, session)}>
            导出 Markdown
          </Button>
        </Space>
      </div>

      {practiceCount === 0 && (
        <Alert
          className="stacked-alert"
          type="info"
          showIcon
          message="还没有单题评分记录，报告会先基于岗位画像和计划生成。完成几道单题训练后再刷新，会更准确。"
        />
      )}

      <Row gutter={[16, 16]} className="overview-row">
        <Col xs={24} lg={7}>
          <Card className="overview-card" title="总分">
            <div className="score-card-body">
              <Progress type="dashboard" percent={activeReport.overallScore} strokeColor="#1f7a8c" />
            </div>
            <div className="summary-list">
              <span>练习记录：{practiceCount} 条</span>
              <span>{activeReport.summary}</span>
            </div>
          </Card>
        </Col>
        <Col xs={24} lg={10}>
          <Card className="overview-card" title="能力雷达图">
            <div className="radar-chart" ref={chartRef} />
          </Card>
        </Col>
        <Col xs={24} lg={7}>
          <Card className="overview-card" title="表达主线">
            <p className="report-quote">{activeReport.thirtySecondRewrite}</p>
          </Card>
        </Col>
      </Row>

      <Row gutter={[16, 16]} className="section-row paired-card-row">
        <Col xs={24} xl={12}>
          <Card className="panel-card" title="优势">
            <List dataSource={activeReport.strengths} renderItem={(item) => <List.Item>{item}</List.Item>} />
          </Card>
        </Col>
        <Col xs={24} xl={12}>
          <Card className="panel-card" title="待补强">
            <List dataSource={activeReport.weaknesses} renderItem={(item) => <List.Item>{item}</List.Item>} />
          </Card>
        </Col>
        <Col xs={24} xl={12}>
          <Card className="panel-card" title="高风险问题">
            <List
              dataSource={activeReport.riskyQuestions}
              renderItem={(item) => (
                <List.Item>
                  <div className="question-item">
                    <Space>
                      <Tag color={item.score >= 70 ? "orange" : "red"}>{item.score}</Tag>
                      <strong>{item.question}</strong>
                    </Space>
                    <span>{item.reason}</span>
                  </div>
                </List.Item>
              )}
            />
          </Card>
        </Col>
        <Col xs={24} xl={12}>
          <Card className="panel-card" title="下一轮训练计划">
            <List dataSource={activeReport.nextPlan} renderItem={(item) => <List.Item>{item}</List.Item>} />
          </Card>
        </Col>
      </Row>
    </section>
  );
}
